export const locationData = [
  {
    name: "Maryland",
    slug: "hibachi-catering-maryland",
    region: "East",
    state: "Maryland",
  },
  {
    name: "Ocean City",
    slug: "hibachi-at-home-ocean-city-md",
    region: "East",
    state: "Maryland",
  },
  {
    name: "DMV(Washington DC, Maryland, North Virginia)",
    slug: "hibachi-chef-dmv",
    region: "East",
    state: "Washington DC",
  },
  {
    name: "Virginia Beach-Hampton Roads",
    slug: "hibachi-catering-virginia",
    region: "East",
    state: "Virginia",
  },
  {
    name: "Richmond",
    slug: "hibachi-catering-richmond",
    region: "East",
    state: "Virginia",
  },
  {
    name: "Fredericksburg",
    slug: "hibachi-at-home-fredericksburg",
    region: "East",
    state: "Virginia",
  },
  {
    name: "Newport News",
    slug: "hibachi-at-home-newport-news",
    region: "East",
    state: "Virginia",
  },
  {
    name: "Raleigh-Durham Area",
    slug: "hibachi-catering-raleigh",
    region: "East",
    state: "North Carolina",
  },
  {
    name: "Outer Bank Area",
    slug: "outerbank",
    region: "East",
    state: "North Carolina",
  },
  {
    name: "Wilmington",
    slug: "hibachi-at-home-wilmington",
    region: "East",
    state: "North Carolina",
  },
  {
    name: "Fayetteville",
    slug: "hibachi-at-home-fayetteville",
    region: "East",
    state: "North Carolina",
  },
  {
    name: "Greensboro/Winston-Salem",
    slug: "hibachi-at-home-greensboro-winston-salem",
    region: "East",
    state: "North Carolina",
  },
  {
    name: "Charlotte",
    slug: "hibachi-at-home-charlotte",
    region: "East",
    state: "North Carolina",
  },
  {
    name: "Durham",
    slug: "hibachi-at-home-durham",
    region: "East",
    state: "North Carolina",
  },
  {
    name: "Charleston-Columbia",
    slug: "hibachi-at-home-charleston",
    region: "South",
    state: "South Carolina",
  },
  {
    name: "Savannah Beach",
    slug: "hibachi-at-home-savannah",
    region: "South",
    state: "South Carolina",
  },
  {
    name: "Myrtle Beach",
    slug: "hibachi-at-home-myrtle-beach",
    region: "South",
    state: "South Carolina",
  },
  {
    name: "Rhode Island",
    slug: "hibachi-at-home-rhode-island",
    region: "East",
    state: "Rhode Island",
  },
  {
    name: "Connecticut",
    slug: "hibachi-catering-connecticut",
    region: "East",
    state: "Connecticut",
  },
  {
    name: "Long Island, New York",
    slug: "hibachi-catering-long-island",
    region: "East",
    state: "New York",
  },
  {
    name: "Rochester-Buffalo, New york",
    slug: "hibachi-at-home-buffalo",
    region: "East",
    state: "New York",
  },
  {
    name: "Syracuse, New York",
    slug: "hibachi-at-home-syracuse",
    region: "East",
    state: "New York",
  },
  {
    name: "New York",
    slug: "new-york-private-chef-book-now",
    region: "East",
    state: "New York",
  },
  {
    name: "New jersey whole state",
    slug: "hibachi-catering-new-jersey",
    region: "East",
    state: "New Jersey",
  },
  {
    name: "Philadelphia metropolitan , PA",
    slug: "philadelphia-private-chef-book-now",
    region: "East",
    state: "Pennsylvania",
  },
  {
    name: "Central PA",
    slug: "hibachi-at-home-central-pa",
    region: "East",
    state: "Pennsylvania",
  },
  {
    name: "Delaware whole state",
    slug: "delaware-private-chef-book-now",
    region: "East",
    state: "Delaware",
  },
  {
    name: "Atlanta",
    slug: "hibachi-at-home-atlanta",
    region: "South",
    state: "Georgia",
  },
  {
    name: "Macon",
    slug: "hibachi-at-home-macon",
    region: "South",
    state: "Georgia",
  },
  {
    name: "Augusta",
    slug: "hibachi-at-home-augusta",
    region: "South",
    state: "Georgia",
  },
  {
    name: "Athens",
    slug: "hibachi-at-home-athens",
    region: "South",
    state: "Georgia",
  },
  {
    name: "Columbus",
    slug: "hibachi-at-home-columbus",
    region: "South",
    state: "Georgia",
  },
  {
    name: "Savannah",
    slug: "hibachi-at-home-savannah-ga",
    region: "South",
    state: "Georgia",
  },
  {
    name: "Miami",
    slug: "miami-private-chef-book-now",
    region: "South",
    state: "Florida",
  },
  {
    name: "Tampa",
    slug: "hibachi-at-home-tampa",
    region: "South",
    state: "Florida",
  },
  {
    name: "Orlando",
    slug: "hibachi-at-home-orlando",
    region: "South",
    state: "Florida",
  },
  {
    name: "Jacksonville",
    slug: "hibachi-at-home-jacksonville",
    region: "South",
    state: "Florida",
  },
  {
    name: "Destin-Pensacola",
    slug: "hibachi-at-home-destin",
    region: "South",
    state: "Florida",
  },
  {
    name: "Sarasota",
    slug: "hibachi-at-home-sarasota",
    region: "South",
    state: "Florida",
  },
  {
    name: "Naples",
    slug: "hibachi-at-home-naples",
    region: "South",
    state: "Florida",
  },
  {
    name: "Fort Myers",
    slug: "hibachi-at-home-fort-myers",
    region: "South",
    state: "Florida",
  },
  {
    name: "Dallas & Fort Worth",
    slug: "hibachi-catering-dallas",
    region: "South",
    state: "Texas",
  },
  {
    name: "Houston",
    slug: "hibachi-catering-houston",
    region: "South",
    state: "Texas",
  },
  {
    name: "Austin",
    slug: "austin-private-chef-book-now",
    region: "South",
    state: "Texas",
  },
  {
    name: "San Antonio",
    slug: "sanantonio-private-chef-book-now",
    region: "South",
    state: "Texas",
  },
  {
    name: "Oklahoma City",
    slug: "hibachi-at-home-okc",
    region: "South",
    state: "Oklahoma",
  },
  {
    name: "Tulsa",
    slug: "hibachi-at-home-tulsa",
    region: "South",
    state: "Oklahoma",
  },
  {
    name: "Little Rock",
    slug: "hibachi-at-home-little-rock",
    region: "South",
    state: "Arkansas",
  },
  {
    name: "Phoenix-Scottdale Area",
    slug: "phoenix-private-chef-book-now",
    region: "West",
    state: "Arizona",
  },
  {
    name: "Tucson",
    slug: "hibachi-catering-tucson",
    region: "West",
    state: "Arizona",
  },
  {
    name: "Sedona-Flagstaff",
    slug: "hibachi-at-home-sedona-flagstaff",
    region: "West",
    state: "Arizona",
  },
  {
    name: "Scottsdale",
    slug: "hibachi-at-home-scottsdale",
    region: "West",
    state: "Arizona",
  },
  {
    name: "Chandler",
    slug: "hibachi-at-home-chandler-az",
    region: "West",
    state: "Arizona",
  },
  {
    name: "Gilbert",
    slug: "hibachi-at-home-gilbert",
    region: "West",
    state: "Arizona",
  },
  {
    name: "Glendale",
    slug: "hibachi-at-home-glendale-az",
    region: "West",
    state: "Arizona",
  },
  {
    name: "Queen Creek",
    slug: "hibachi-at-home-queens",
    region: "West",
    state: "Arizona",
  },
  {
    name: "Los Angeles",
    slug: "hibachi-at-home-los-angeles",
    region: "West",
    state: "California",
  },
  {
    name: "San Diego",
    slug: "hibachi-at-home-san-diego",
    region: "West",
    state: "California",
  },
  {
    name: "Bakersfield",
    slug: "hibachi-at-home-bakersfield",
    region: "West",
    state: "California",
  },
  {
    name: "Lancaster",
    slug: "hibachi-at-home-lancaster",
    region: "West",
    state: "California",
  },
  {
    name: "Santa Clarita",
    slug: "hibachi-at-home-santa-clarita",
    region: "West",
    state: "California",
  },
  {
    name: "Thousand Oaks",
    slug: "hibachi-at-home-thousand-oaks",
    region: "West",
    state: "California",
  },
  {
    name: "Fresno",
    slug: "hibachi-at-home-fresno-ca",
    region: "West",
    state: "California",
  },
  {
    name: "Sacramento",
    slug: "hibachi-at-home-sacramento-ca",
    region: "West",
    state: "California",
  },
  {
    name: "Las Vegas",
    slug: "hibachi-at-home-las-vegas",
    region: "West",
    state: "Nevada",
  },
  {
    name: "Henderson",
    slug: "hibachi-at-home-henderson",
    region: "West",
    state: "Nevada",
  },
  {
    name: "North Las Vegas",
    slug: "hibachi-at-home-north-las-vegas",
    region: "West",
    state: "Nevada",
  },
  {
    name: "Paradise",
    slug: "hibachi-at-home-paradise",
    region: "West",
    state: "Nevada",
  },
  {
    name: "Spring Valley",
    slug: "hibachi-at-home-spring-valley",
    region: "West",
    state: "Nevada",
  },
  {
    name: "Seattle",
    slug: "hibachi-at-home-seattle",
    region: "West",
    state: "Washington",
  },
  {
    name: "Tacoma",
    slug: "hibachi-at-home-tacoma",
    region: "West",
    state: "Washington",
  },
  {
    name: "Vancouver",
    slug: "hibachi-at-home-vancouver",
    region: "West",
    state: "Washington",
  },
  {
    name: "Portland",
    slug: "hibachi-at-home-portland-or",
    region: "West",
    state: "Oregon",
  },
  {
    name: "Salem",
    slug: "hibachi-at-home-salem-or",
    region: "West",
    state: "Oregon",
  },
  {
    name: "Eugene",
    slug: "hibachi-at-home-eugene",
    region: "West",
    state: "Oregon",
  },
  {
    name: "Denver",
    slug: "hibachi-at-home-denver",
    region: "West",
    state: "Colorado",
  },
  {
    name: "Colorado Springs",
    slug: "hibachi-at-home-colorado-springs",
    region: "West",
    state: "Colorado",
  },
  {
    name: "Aurora",
    slug: "hibachi-at-home-aurora",
    region: "West",
    state: "Colorado",
  },
  {
    name: "Fort Collins",
    slug: "hibachi-at-home-fort-collins",
    region: "West",
    state: "Colorado",
  },
  {
    name: "Salt Lake City",
    slug: "hibachi-at-home-salt-lake-city",
    region: "West",
    state: "Utah",
  },
  {
    name: "Provo",
    slug: "hibachi-at-home-provo",
    region: "West",
    state: "Utah",
  },
  {
    name: "West Jordan",
    slug: "hibachi-at-home-west-jordan",
    region: "West",
    state: "Utah",
  },
  {
    name: "Albuquerque",
    slug: "hibachi-at-home-albuquerque",
    region: "West",
    state: "New Mexico",
  },
  {
    name: "Santa Fe",
    slug: "hibachi-at-home-santa-fe",
    region: "West",
    state: "New Mexico",
  },
  {
    name: "Detroit",
    slug: "hibachi-at-home-detroit",
    region: "Midwest",
    state: "Michigan",
  },
  {
    name: "Ann Arbor",
    slug: "hibachi-at-home-ann-arbor",
    region: "Midwest",
    state: "Michigan",
  },
  {
    name: "Grand Rapids",
    slug: "hibachi-at-home-grand-rapids",
    region: "Midwest",
    state: "Michigan",
  },
  {
    name: "Chicago",
    slug: "hibachi-at-home-chicago",
    region: "Midwest",
    state: "Illinois",
  },
  {
    name: "Aurora",
    slug: "hibachi-at-home-aurora-il",
    region: "Midwest",
    state: "Illinois",
  },
  {
    name: "Naperville",
    slug: "hibachi-at-home-naperville",
    region: "Midwest",
    state: "Illinois",
  },
  {
    name: "Joliet",
    slug: "hibachi-at-home-joliet",
    region: "Midwest",
    state: "Illinois",
  },
  {
    name: "Indianapolis",
    slug: "hibachi-at-home-indianapolis",
    region: "Midwest",
    state: "Indiana",
  },
  {
    name: "Fort Wayne",
    slug: "hibachi-at-home-fort-wayne",
    region: "Midwest",
    state: "Indiana",
  },
  {
    name: "Columbus",
    slug: "hibachi-at-home-columbus-oh",
    region: "Midwest",
    state: "Ohio",
  },
  {
    name: "Cleveland",
    slug: "hibachi-at-home-cleveland",
    region: "Midwest",
    state: "Ohio",
  },
  {
    name: "Cincinnati",
    slug: "hibachi-at-home-cincinnati",
    region: "Midwest",
    state: "Ohio",
  },
  {
    name: "Toledo",
    slug: "hibachi-at-home-toledo",
    region: "Midwest",
    state: "Ohio",
  },
  {
    name: "Dayton",
    slug: "hibachi-at-home-dayton",
    region: "Midwest",
    state: "Ohio",
  },
  {
    name: "Kansas City",
    slug: "hibachi-at-home-kansas-city",
    region: "Midwest",
    state: "Kansas/Missouri",
  },
  {
    name: "St Louis",
    slug: "hibachi-at-home-st-louis",
    region: "Midwest",
    state: "Missouri",
  },
  {
    name: "Nashville",
    slug: "hibachi-at-home-nashville",
    region: "Midwest",
    state: "Tennessee",
  },
  {
    name: "Memphis",
    slug: "hibachi-at-home-memphis",
    region: "Midwest",
    state: "Tennessee",
  },
  {
    name: "Knoxville",
    slug: "hibachi-at-home-knoxville",
    region: "Midwest",
    state: "Tennessee",
  },
  {
    name: "Chattanooga",
    slug: "hibachi-at-home-chattanooga",
    region: "Midwest",
    state: "Tennessee",
  },
  {
    name: "Louisville",
    slug: "hibachi-at-home-louisville",
    region: "Midwest",
    state: "Kentucky",
  },
  {
    name: "Lexington",
    slug: "hibachi-at-home-lexington",
    region: "Midwest",
    state: "Kentucky",
  },
  {
    name: "Milwaukee",
    slug: "hibachi-at-home-milwaukee",
    region: "Midwest",
    state: "Wisconsin",
  },
  {
    name: "Madison",
    slug: "hibachi-at-home-madison",
    region: "Midwest",
    state: "Wisconsin",
  },
  {
    name: "Minneapolis",
    slug: "hibachi-at-home-minneapolis",
    region: "Midwest",
    state: "Minnesota",
  },
  {
    name: "St Paul",
    slug: "hibachi-at-home-st-paul",
    region: "Midwest",
    state: "Minnesota",
  },
]
